name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.17.0'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar el servidor (opcional para test)
      run: |
        node server.js &
        sleep 5
        curl http://localhost:3000/ping
